feature: Improve Logging of `tf`
ethereum/execution-spec-tests pull request #114
Opened 2023-04-25 23:19 UTC by spencer-tb

This PR adds the minimal changes from #82 for now before we upgrade the repo to pytest.

Reference specs are updated for relevant Shanghai eips as they have been moved final. Commit example: https://github.com/ethereum/EIPs/commit/5ccb61c9d28348c07a095b0b478cf52c38ab107d

Reference spec checks are now ignored for specific modules: `["vm", "example", "security"]`.

Logging is set to `INFO` level in `logger.cfg`. We now have a very clean output so if we reference spec warnings it will be very easy to see.

2023-04-28 13:25 UTC, danceratopz commented
Really like the format/colorisation! Works for me with the change above. We can still use this when we move to pytest; pytest will write the logs directed to stdout in the console if it's ran with the `-s` flag.

2023-05-03 15:47 UTC, marioevz requested changes
Just one comment regarding the dependencies.

2023-05-03 15:47 UTC, marioevz commented on tox.ini
> +    colorlog
I think we need this dependency also in the `setup.cfg`.

I'm getting the following error locally:

```
ModuleNotFoundError: No module named 'colorlog'
```

2023-05-03 21:07 UTC, marioevz commented on setup.cfg
> +    colorlog>=6.7.0
It's still failing in my local setup :/

I moved it to the `install_requires` category and it seems to be working fine.

2023-05-03 21:13 UTC, marioevz approved these changes
Thanks!

2023-05-03 21:13 UTC, merged