add eip6780 test cases which use revert
ethereum/execution-spec-tests pull request #270
Opened 2023-08-24 06:44 UTC by jwasinger

2023-08-31 16:26 UTC, marioevz requested changes
Looks very good, just some comments that would be nice to have.

2023-08-31 16:26 UTC, marioevz commented on tests/cancun/eip6780_selfdestruct/test_selfdestruct_revert.py
> +    entry_code += Op.POP()
```suggestion
entry_code += Op.SSTORE(
        0,
        Op.CREATE(
            0, 0, len(bytes(selfdestruct_with_transfer_contract_initcode))  # Value  # Offset
        ),
    )
```
We could save the address and verify it for good measure. I think this just requires adding a return at the end of `entry_code` to be able to verify `storage={0: selfdestruct_with_transfer_contract_address}`.

2023-09-05 15:37 UTC, jwasinger commented on tests/cancun/eip6780_selfdestruct/test_selfdestruct_revert.py
> +
You are correct.  I did accidentally omit the call to `A.selfdestruct` from the outer call.

2023-09-05 18:45 UTC, jwasinger commented on tests/cancun/eip6780_selfdestruct/test_selfdestruct_revert.py
> +                return(0, 0)
I've added counters for invocations to transfer/selfdestruct in this contract.

2023-09-06 15:33 UTC, jwasinger commented
@marioevz I have addressed your points above and I think this is ready for further review when you get the time.

2023-09-06 15:49 UTC, marioevz commented
> @marioevz I have addressed your points above and I think this is ready for further review when you get the time.

Thanks! I'll try to get it done today :)

2023-09-07 02:25 UTC, marioevz approved these changes
LGTM! Thanks for implementing these

2023-09-07 02:44 UTC, merged