Add docstrings to all opcodes in the Opcodes Enum
ethereum/execution-spec-tests pull request #424
Opened 2024-02-04 07:16 UTC by ThreeHrSleep

## 🗒️ Description

Added docstrings to most of the opcodes in the Opcodes Enum.
Left `TSTORE`,`TLOAD`,`SENDALL`,`RJUMPI`,`RJUMPV` incomplete due to confusion
## 🔗 Related Issues
#383 

## ✅ Checklist
- [ ] All: Set appropriate labels for the changes.
- [X] All: Considered squashing commits to improve commit history.
- [ ] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).
- [ ] All: Considered updating the online docs in the [./docs/](../docs/) directory.
- [ ] Tests: Included the type and version of evm t8n tool used to locally execute test cases:  e.g., ref with commit hash or geth 1.13.1-stable-3f40e65.
- [X] Tests: Ran `mkdocs serve` locally and verified the auto-generated docs for new tests in the [Test Case Reference](https://ethereum.github.io/execution-spec-tests/main/tests/) are correctly formatted.

2024-02-06 01:37 UTC, marioevz reviewed
Looks amazing! Thanks for this. I added some minor comments before we can merge.

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +STOP = Opcode(0x00)
Indentation is missing in this and all subsequent lines.
```suggestion
    STOP = Opcode(0x00)
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +- Source: [evm.codes/#5A](https://www.evm.codes/#5A)
Typo.

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +DUP15(a, b, c) = c, a, b, c
```suggestion
DUP3(a, b, c) = c, a, b, c
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +DUP15(value1, value2, value3, value) = value, value2, value3, value
```suggestion
DUP4(value1, value2, value3, value) = value, value1, value2, value3, value
```
Similar issue on the rest of the DUP opcodes.

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +SWAP3(a, value2, value3, b) = b value2, value3, a
```suggestion
SWAP3(a, value2, value3, b) = b, value2, value3, a
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +SWAP4(a, value2, value3, value4, b) = b value2, value3, value4, a
```suggestion
SWAP4(a, value2, value3, value4, b) = b, value2, value3, value4, a
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +LOG3(offset, size)
```suggestion
LOG0(offset, size) 
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +Frontier
```suggestion
Cancun
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +STOP()
```suggestion
STOP()
```
Tox (the linting and code format tool we currently use) is complaining about trailing white spaces in some of the lines.

In vscode you could search for `\s+$` to automatically remove all of these.

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +Load a value from the storage at the specified key.
```suggestion
Load a value from the transient storage at the specified key.
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +
```suggestion
Cancun
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +Store a value in the storage at the specified key.
```suggestion
Store a value in the transient storage at the specified key.
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +
```suggestion
Cancun
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +Frontier
```suggestion
Cancun
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +Frontier
```suggestion
Shanghai
```

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +Revolution
```suggestion
N/A
```
It's supposed to be included with EOF, which is aimed for the Prague hard-fork, but until it's formally considered for inclusion we can just put `N/A` here.

2024-02-06 01:37 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +RJUMP = Opcode(0xE0, data_portion_length=2)
Description for `RJUMP`, `RJUMPI` and `RJUMPV` can be found here: https://notes.ethereum.org/@ipsilon/mega-eof-specification#New-Behavior

2024-02-06 14:08 UTC, ThreeHrSleep commented
Thanks for reviewing! 
Implemented the suggested changes.
Please lmk if there's anything that needs to be modified :)

2024-02-09 10:05 UTC, danceratopz requested changes
This is looking really great, thanks a lot for adding this! :100: 

In general, `tox` is really helpful to make sure no errors have crept in. The framework-specific checks (`tox -e framework`) and the tests checks (`tox -e tests`) caught the error in the PUSH opcode values (see below). Docs here: https://ethereum.github.io/execution-spec-tests/v2.1.0/writing_tests/verifying_changes/

You will probably come across all sort of whitespace / max-line-length errors when you try to run tox...

These could be either handled in your script, by wrapping the new docstring lines at the relevant column (99) or by using VS Code and plugins. In addition to the repo's VS Code setup you might need a plugin like https://stkb.github.io/Rewrap/ to help with bullet point formatting/line-wrapping.

If you feel it's worth getting VS code setup to handle these, see https://ethereum.github.io/execution-spec-tests/v2.1.0/getting_started/setup_vs_code/.

If not (or if your having other issues), feel free to ping me, and I'm happy to help with formatting to get this over the finish line! :slightly_smiling_face:

2024-02-10 01:53 UTC, ThreeHrSleep commented
Thanks a lot for pointing out the problems @danceratopz !! :heart: 
I'll try to get the VS Code setup done,handle the whitespaces & fix the issue with PUSH
will definitely let you know if I get stuck somewhere :)

2024-02-13 18:54 UTC, marioevz requested changes
Some more comments thanks!

I think you should be able to just batch-commit all the comments directly from here.

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +    100
```suggestion
    warm: 100
    cold: 2100
```

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +    100
```suggestion
    set: 20000
    reset: 2900
```
There's a lot of nuances to the actual gas cost of this opcode, but we can leave this snippet as this for now.

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +    - Source: [evm.codes/#5A](https://www.evm.codes/#5A)
```suggestion
    - gas_remaining: remaining gas for the current call frame
```

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +
```suggestion
    Cancun
```

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +
```suggestion
    Cancun
```

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +    Frontier
```suggestion
    Cancun
```

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +    Frontier
```suggestion
    Shanghai
```

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +    Revolution
```suggestion
    
```

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +    Homestead
```suggestion
    Frontier
```

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +    SENDALL(to) = success
```suggestion
    SENDALL(to)
```

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +    Send all ether to the target address.
```suggestion
    Send all ether to the target address and halt execution.
```

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +
```suggestion
    5000
```

2024-02-13 18:54 UTC, marioevz commented on src/ethereum_test_tools/vm/opcode.py
> +    Source: [eips.ethereum.org/EIPS/eip-4758](https://eips.ethereum.org/EIPS/eip-4758)
```suggestion
    Source: [eips.ethereum.org/EIPS/eip-6780](https://eips.ethereum.org/EIPS/eip-6780)
```

2024-02-16 03:17 UTC, ThreeHrSleep commented
Thanks ! 
and sorry for making so many mistakes in the PR :sweat_smile:

2024-02-21 01:20 UTC, marioevz approved these changes

2024-02-21 01:21 UTC, marioevz commented
Hey @danceratopz I think we are unable to merge unless you approve the requested changes, if you'd like to give this another look :+1:

2024-02-22 16:23 UTC, danceratopz requested changes
Sorry for the hold up! Looking good, thank you once again! 

I replaced the unnecessary UTF8 characters in 6864f5d9 (`’` -> `'`). Otherwise, a few fixes/suggestions below!

2024-02-22 16:23 UTC, danceratopz commented on src/ethereum_test_tools/vm/opcode.py
> +    20
```suggestion
    2
```

2024-02-22 16:23 UTC, danceratopz commented on src/ethereum_test_tools/vm/opcode.py
> +    reset: 2900
```suggestion
    static_gas = 0

    if value == current_value
        if key is warm
            base_dynamic_gas = 100
        else
            base_dynamic_gas = 100
    else if current_value == original_value
        if original_value == 0
            base_dynamic_gas = 20000
        else
            base_dynamic_gas = 2900

    if key is cold:
        base_dynamic_gas += 2100
```

2024-02-22 16:23 UTC, danceratopz commented on src/ethereum_test_tools/vm/opcode.py
> +    reset: 2900
Maybe too much :see_no_evil: :laughing:

2024-02-22 16:23 UTC, danceratopz commented on src/ethereum_test_tools/vm/opcode.py
> +    0
```suggestion
    memory_expansion_cost
```

2024-02-27 09:36 UTC, danceratopz approved these changes

2024-02-27 09:38 UTC, danceratopz commented
> Hey @danceratopz I think we are unable to merge unless you approve the requested changes, if you'd like to give this another look 👍

Hey @marioevz, @spencer-tb's doing a last pass :sweat_smile: and will give some more input sooon, but I've approved the requested changes to avoid blocking!

2024-02-27 11:29 UTC, spencer-tb commented
I added some additional tweaks in: [035821f](https://github.com/ethereum/execution-spec-tests/pull/424/commits/035821faec0443b191b4bddc5f4c91828217dae1)

- General clean-up, removing `.`'s and newlines etc,
- Fixed forkname mismatches,
- Clean up of swap and push opcodes,
- Gas formatting clean up (the markdown wasn't rendering nicely in vscode),
- Ordered the opcodes,
- Removed SENDALL as we don't use it anywhere,
- Tox fixes.

2024-02-27 11:31 UTC, spencer-tb approved these changes
Cheeky approve after my commit :D

2024-02-27 11:56 UTC, danceratopz commented
Amazing. The most commented PR in the history of execution-spec-tests! Thanks again @ThreeHrSleep!

2024-02-27 11:56 UTC, merged