Test EIP-2929
ethereum/execution-spec-tests pull request #689
Opened 2024-07-17 17:58 UTC by SamWilsn

## 🗒️ Description

Adds a test related to EIP-2929.

## 🔗 Related Issues

Inspired by https://github.com/ethereum/execution-specs/issues/978.

## ✅ Checklist
- [ ] All: Set appropriate labels for the changes.
- [ ] All: Considered squashing commits to improve commit history.
- [ ] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).
- [ ] All: Considered updating the online docs in the [./docs/](/ethereum/execution-spec-tests/blob/main/docs/) directory.
- [ ] Tests: All converted JSON/YML tests from [ethereum/tests](/ethereum/tests) have been added to [converted-ethereum-tests.txt](/ethereum/execution-spec-tests/blob/main/converted-ethereum-tests.txt).
- [ ] Tests: A PR with removal of converted JSON/YML tests from [ethereum/tests](/ethereum/tests) have been opened.
- [ ] Tests: Included the type and version of evm t8n tool used to locally execute test cases:  e.g., ref with commit hash or geth 1.13.1-stable-3f40e65.
- [ ] Tests: Ran `mkdocs serve` locally and verified the auto-generated docs for new tests in the [Test Case Reference](https://ethereum.github.io/execution-spec-tests/main/tests/) are correctly formatted.

2025-10-02 08:01 UTC, LouisTsai-Csie requested changes
Thanks @SamWilsn for the PR. I’ve added some comments, please let me know if I’ve misunderstood the intention of the test.

2025-10-02 08:01 UTC, LouisTsai-Csie commented on tests/berlin/eip2929_state_gas/test_call.py
> +    )
I read the discussion in the PR, and my understanding is that even if a `CALL` is aborted exceptionally, the target address should still be marked as **warm**.

The test is intended to reproduce that scenario, an aborted CALL followed by a `BALANCE` to verify the warm access gas cost. However, in the current implementation, `BALANCE` will always succeed, and we do not collect the gas consumption during execution, there is no storage validation for `contract_address` either.

I also recalculated the gas usage and noticed it does not align with the `gas_limit` specified in the `tx` object. That said, the provided gas is still sufficient even if the storage access were charged at the cold access cost. (Please correct me if I’ve misunderstood anything.)

I would suggest the following change that measure the gas cost for `BALANCE` operation leverage the `CodeGasMeasure` helper.

```python
@pytest.mark.valid_from("Berlin")
def test_call_insufficient_balance(
    state_test: StateTestFiller, pre: Alloc, env: Environment, fork: Fork
):
    """
    Test a regular CALL to see if it warms the destination with insufficient
    balance.
    """
    gas_costs = fork.gas_costs()
    destination = pre.fund_eoa(1)
    contract_address = pre.deploy_contract(
        # Perform the aborted external calls
        Op.SSTORE(
            0,
            Op.CALL(
                gas=Op.GAS,
                address=destination,
                value=1,
                args_offset=0,
                args_size=0,
                ret_offset=0,
                ret_size=0,
            ),
        )
         # Measure the gas cost for BALANCE operation
        + CodeGasMeasure(
            code=Op.BALANCE(destination),
            overhead_cost=gas_costs.G_VERY_LOW,  # PUSH20 costs 3 gas
            extra_stack_items=1,  # BALANCE puts balance on stack
            sstore_key=1,
        ),
        balance=0,
    )

    tx = Transaction(
        to=contract_address,
        gas_limit=env.gas_limit,
        sender=pre.fund_eoa(),
    )

    post = {
        destination: Account(
            balance=1,
        ),
        contract_address: Account(
            storage={
                0: 0, # The CALL is aborted
                1: gas_costs.G_WARM_ACCOUNT_ACCESS,  # Warm access cost
            },
        ),
    }
    state_test(env=env, pre=pre, post=post, tx=tx)
```

Moreover, it would be nice if this test could be moved under `tests/berlin/eip2929_gas_cost_increases`, or there would be duplicate folder for eip2929.

2025-10-08 10:50 UTC, spencer-tb reviewed
Test is failing when filling for Osaka for me!

2025-10-08 10:53 UTC, spencer-tb approved these changes
LGTM! Added the fix.

2025-10-08 10:53 UTC, spencer-tb commented on tests/berlin/eip2929_gas_cost_increases/test_call.py
> +        gas_limit=env.gas_limit,
```suggestion
        gas_limit=100_000,
```

2025-10-08 11:16 UTC, merged