feat(transition_tool): Support EELS resolver in daemon mode
ethereum/execution-spec-tests pull request #792
Opened 2024-09-06 20:51 UTC by petertdavies

## 🗒️ Description
Implement the EELS daemon support and fix various bugs and deficiencies found during testing EELS daemon support. Pre-Prague forks can be filled by installing the [EELS resolver](https://github.com/petertdavies/ethereum-spec-evm-resolver) and running `fill --evm-bin=ethereum-spec-evm-resolver`.

Currently Prague support is broken due to issues in EELS.

## 🔗 Related Issues
Most of the code in this PR was implemented the draft PR #453 

## ✅ Checklist
- [ ] All: Set appropriate labels for the changes.
- [ ] All: Considered squashing commits to improve commit history.
- [ ] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).
- [ ] All: Considered updating the online docs in the [./docs/](/ethereum/execution-spec-tests/blob/main/docs/) directory.
- [ ] Tests: All converted JSON/YML tests from [ethereum/tests](/ethereum/tests) have been added to [converted-ethereum-tests.txt](/ethereum/execution-spec-tests/blob/main/converted-ethereum-tests.txt).
- [ ] Tests: A PR with removal of converted JSON/YML tests from [ethereum/tests](/ethereum/tests) have been opened.
- [ ] Tests: Included the type and version of evm t8n tool used to locally execute test cases:  e.g., ref with commit hash or geth 1.13.1-stable-3f40e65.
- [ ] Tests: Ran `mkdocs serve` locally and verified the auto-generated docs for new tests in the [Test Case Reference](https://ethereum.github.io/execution-spec-tests/main/tests/) are correctly formatted.

2024-09-06 22:15 UTC, spencer-tb commented
Thanks! :D
I added some extra tweaks here: https://github.com/petertdavies/execution-spec-tests/pull/1

Mostly some debug dir functionality!

2024-09-18 15:33 UTC, danceratopz reviewed
LGTM! Really nice to start using EELS as the default `t8n` tool! Will make a few updates to the docs and then I think we're good to go!

2024-09-18 15:33 UTC, danceratopz commented on src/evm_transition_tool/besu.py
> +    t8n_use_stream = True
We can remove this line for Besu, which doesn't use stream (file IO); it has a `t8n-server`. However, it overrides `evaluate()` to implement communication with its `t8n-server`. This means it doesn't make use of either `t8n_use_stream` or `t8n_use_server`; they can be left as the defaults. This flag is simply unused for Besu.

```suggestion
```

2024-09-18 15:33 UTC, danceratopz commented on src/evm_transition_tool/besu.py
> +    t8n_use_stream = True
I made a follow-up ticket to potentially clean-up these two t8n server evaluate methods #818, it's beyond the scope of this PR.

2024-09-18 15:33 UTC, danceratopz commented on uv.lock
> -
Very nice to be able to drop the dependency on `consensus-specs`.

2024-09-19 08:24 UTC, danceratopz commented on uv.lock
> -
@marioevz we can bump the version of trie now to remove warnings in the framework pytest summary and doc flow (in a follow-up PR).

2024-09-19 14:27 UTC, danceratopz commented
@marioevz @spencer-tb: @petertdavies hardened the resolver and framework tests now run with EELS (ci is :green_circle:) :partying_face: I'll finish updating the docs then we're ready to go!

2024-09-20 08:06 UTC, danceratopz requested changes
Just diff'd the fixtures between EELS and geth - we have parity :partying_face: 
(excluding Constantinople, which is not supported by EELS).

Verified via:
```bash
rm -rf fixtures-geth; fill --output=fixtures-geth -k "not fork_Constantinople-" --evm-bin=./evm -n auto
rm -rf fixtures-eels; fill --output=fixtures-eels -k "not fork_Constantinople-" -n 8
uv run hasher fixtures-geth > hasher-geth.txt
uv run hasher fixtures-eels > hasher-eels.txt
diff hasher-eels.txt hasher-geth.txt
```

(#802 should make they hacky test path arg passed to `-k` redundant).

I do still have sporadic fails using the `ethereum-spec-evm-resolver` when I use `-n auto` (which uses 16 threads on my machine). `-n 8` does seem safer, but we should try to harden it even more, see also comment below.

Btw, we currently report the filling tool to be "ethereum-spec-evm-resolver 0.0.1", it would be helpful if we could report the resolved t8n as well, cf petertdavies/ethereum-spec-evm-resolver/issues/2.

2024-09-20 08:06 UTC, danceratopz commented on .github/configs/evm-impl.yaml
> +  x-dist: auto
Attempt to reduce sporadic fails?
```suggestion
  x-dist: 8
```

2024-09-20 08:06 UTC, danceratopz commented on .github/configs/evm.yaml
> +  ref: null
Are we ready for this?

2024-09-20 13:01 UTC, spencer-tb commented on docs/CHANGELOG.md
> +- ✨ Fill test fixtures using EELS by default. EEST now uses the [`ethereum-specs-evm-resolver`](https://github.com/petertdavies/ethereum-spec-evm-resolver) with the EELS daemon which provides a speed
Hmm this makes me think we have **could** additionally hav a bug somewhere in our code! Going to try with the previous closed PR (not using resolver)!

2024-09-23 08:04 UTC, danceratopz commented on .github/configs/evm-impl.yaml
> +  x-dist: auto
Since Peter's resolver hardening, this PR now has 8 green Github actions, I think we can skip this :slightly_smiling_face:

2024-09-23 08:18 UTC, danceratopz commented on .github/configs/evm-impl.yaml
> +  x-dist: auto
Jinxed it, sporadic fail encountered during framework tests. The Github actions runner is using 4 runners with `-n auto` though, so we def shouldn't apply this change.

2024-09-23 08:30 UTC, danceratopz commented on docs/CHANGELOG.md
> +- ✨ Fill test fixtures using EELS by default. EEST now uses the [`ethereum-specs-evm-resolver`](https://github.com/petertdavies/ethereum-spec-evm-resolver) with the EELS daemon which provides a speed
@spencer-tb This def isn't particular to the resolver. I have similar behavior on main with ad69c4bfd and geth. Could simply be down to CPU contention.

2024-09-23 08:52 UTC, danceratopz commented on .github/configs/evm-impl.yaml
> +  x-dist: auto
Perhaps the framework tests (in `tox -e framework`) could potentially briefly stress the resolver more than filling tests (in `tox -e tests`).

Some of the framework tests `fill` by calling the transition tool's `evaluate()` directly. These won't have the normal overhead incurred when filling and might result in more concurrent requests to the resolver.

2024-09-23 09:21 UTC, danceratopz commented on .github/configs/evm-impl.yaml
> +  x-dist: auto
Marked framework tests that call `fill` or `generate()` to only run in serial in `tox -e framework`, 4aaf99fdc.

2024-09-27 08:33 UTC, danceratopz reviewed
746ce99fa7045e2250512ad1acaa8f2dc36e4b10 with petertdavies/ethereum-spec-evm-resolver/pull/3 seem to have resolved the `OSError: AF_UNIX path too long` on macOS. 

Unfortunately, subsequent build have now failed due to a resolver issue on Linux in the framework tests.

```
 >       sock.connect(socket_path)
E       ConnectionRefusedError: [Errno 111] Connection refused

.tox/framework/lib/python3.12/site-packages/requests_unixsocket/adapters.py:35: ConnectionRefusedError
```

https://github.com/ethereum/execution-spec-tests/actions/runs/11066974159/job/30749330866:
```
FAILED src/ethereum_test_specs/tests/test_expect.py::test_post_account_mismatch[pre3-post3-UnexpectedAccount]
FAILED src/ethereum_test_tools/tests/test_code.py::test_switch[no-calldataload-condition-met-different-length-actions]
```

https://github.com/ethereum/execution-spec-tests/actions/runs/11067119568/job/30749785674
```
FAILED src/ethereum_test_specs/tests/test_fixtures.py::test_fill_blockchain_invalid_txs[London-False-blockchain_london_invalid_filled.json]
FAILED src/ethereum_test_specs/tests/test_expect.py::test_post_code_value_mismatch[pre1-post1]
```

2024-09-27 08:33 UTC, danceratopz commented on pyproject.toml
> +    "ethereum-spec-evm-resolver @ git+https://github.com/danceratopz/ethereum-spec-evm-resolver@fix/shorten-socket-name",
We should revert this change before merge.

2024-09-27 09:13 UTC, danceratopz commented on .github/configs/evm-impl.yaml
> +  x-dist: auto
I'm not sure it's these tests that are the problem any more. Resolving for now and taking the discussion below, cf https://github.com/ethereum/execution-spec-tests/pull/792#pullrequestreview-2333121342

2024-09-27 12:44 UTC, danceratopz commented on pyproject.toml
> +    "ethereum-spec-evm-resolver @ git+https://github.com/danceratopz/ethereum-spec-evm-resolver@fix/shorten-socket-name",
Done.

2024-09-27 16:00 UTC, marioevz approved these changes
Looks good to me! Great work on this, thanks so much!

2024-09-27 17:49 UTC, danceratopz approved these changes
LGTM!

2024-09-27 17:49 UTC, merged