🐞 fix: Datatable custom filter and other goodies
ethereum/execution-spec-tests pull request #853
Opened 2024-10-01 06:50 UTC by raxhvl

## 🗒️ Description
Fixes:
-  Issues with custom fork and test filters.
-  Resolved a bug causing the datatable to break when changing entries per page.

Enhancements:

-  Upgraded jQuery from 3.5.1 to 3.7.1.
-  Upgraded DataTables from 1.10.21 to 2.1.7.
-  Migrated to minified scripts / css where possible for faster page load.
-  nit: Renamed `javascripts` folder to `js` and `stylesheets` to `css` as per convention.
-  Added a plugin for searchable dropdowns.

Please review the changes. Thank you!

![image](https://github.com/user-attachments/assets/7f3608d5-1fd3-4e2c-8e5a-02feae69b184)

## 🔗 Related Issues
#842 

## ✅ Checklist
- [ ] All: Set appropriate labels for the changes.
- [ ] All: Considered squashing commits to improve commit history.
- [ ] All: Added an entry to [CHANGELOG.md](/ethereum/execution-spec-tests/blob/main/docs/CHANGELOG.md).
- [ ] All: Considered updating the online docs in the [./docs/](/ethereum/execution-spec-tests/blob/main/docs/) directory.
- [ ] Tests: All converted JSON/YML tests from [ethereum/tests](/ethereum/tests) have been added to [converted-ethereum-tests.txt](/ethereum/execution-spec-tests/blob/main/converted-ethereum-tests.txt).
- [ ] Tests: A PR with removal of converted JSON/YML tests from [ethereum/tests](/ethereum/tests) have been opened.
- [ ] Tests: Included the type and version of evm t8n tool used to locally execute test cases:  e.g., ref with commit hash or geth 1.13.1-stable-3f40e65.
- [ ] Tests: Ran `mkdocs serve` locally and verified the auto-generated docs for new tests in the [Test Case Reference](https://ethereum.github.io/execution-spec-tests/main/tests/) are correctly formatted.

2024-10-01 07:28 UTC, danceratopz commented
Hey @raxhvl, thanks for this! We had some issues with CI yesterday due to some upstream changes. Let me sort that out in [docs/include-all-parameters-in-test-parameter-datatables](https://github.com/ethereum/execution-spec-tests/tree/docs/include-all-parameters-in-test-parameter-datatables).

2024-10-01 07:38 UTC, raxhvl commented
Just noticed that filters doesn't play nice with the search. Looking into it.

2024-10-01 08:16 UTC, danceratopz reviewed
Thanks, this looks excellent so far! Much cleaner handling of the data table initialization. I really like the select styling. Just one small comment regarding the standalone html pages.

2024-10-01 08:16 UTC, danceratopz commented on docs/javascripts/site.js
> +document$.subscribe(() => {
This breaks the data table initialization in the standalone pages as `site.js` also gets included there:
https://github.com/raxhvl/execution-spec-tests/blob/0c2549d6fc42a59b6a338e3f8821da722ce95827/docs/templates/function.html.j2#L24

2024-10-01 17:58 UTC, raxhvl commented
@danceratopz I think you will have to merge main again. Now search works within filter which is nice. Plus small updates to the UI. I'm done unless you have feedback.

2024-10-02 06:57 UTC, danceratopz requested changes
Thanks @raxhvl! The tables within the mkdocs pages look wonderful - love it!

Just one comment on the standalone pages. If there's no easy fix, we could consider splitting `function_parameter_datatable.html.j2` into a base template that would contain almost the logic and two derived pages, one for mkdocs, one for standalone. The only difference between the two would be whether to include the SVG, or not.

2024-10-02 06:57 UTC, danceratopz commented on docs/templates/function_parameter_datatable.html.j2
> +            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
Here's how this renders on the standalone page (Firefox):
![image](https://github.com/user-attachments/assets/1b1fe021-da32-4fae-9d3e-c7efb138c827)

2024-10-02 11:46 UTC, raxhvl commented
> Thanks @raxhvl! The tables within the mkdocs pages look wonderful - love it!
> 
> Just one comment on the standalone pages. If there's no easy fix, we could consider splitting `function_parameter_datatable.html.j2` into a base template that would contain almost all the logic and add two derived templates, one for mkdocs, one for standalone. The only difference between the two would be whether to include the SVG, or not.

It was a small fix - I copied over relevant css code from mkdocs to custom.css so it applies at both places now. Also, the standalone page was too wide and close to the browser boundary; I made it a little more compact - let me know if that looks okay

2024-10-02 12:30 UTC, merged